import localFont from "next/font/local";
import "./globals.css";
import Home from "./page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {
          <Home/>
        }
      </body>
    </html>
  );
}
